-- ACCOUNTS
INSERT INTO ACCOUNT(ID, ACCOUNTID, PASSWORD, ROLE) VALUES(1, 'mlovrekov', '$2a$10$4wUDRII5yHHNwY5BB4/Ct.GEIB1jXYoFYoBiRD12Zcy2PZBRxfMNy', 'USER');
INSERT INTO ACCOUNT(ID, ACCOUNTID, PASSWORD, ROLE) VALUES(2, 'testuser', '$2a$10$4wUDRII5yHHNwY5BB4/Ct.GEIB1jXYoFYoBiRD12Zcy2PZBRxfMNy', 'USER');
-- URLS
INSERT INTO URL(ID, ORIGINAL_URL, TOKEN, REDIRECT_TYPE, HIT_COUNT, ACCOUNT_ID) VALUES(1, 'http://test.com', 'AbCd3F', 302, 1, 1);
INSERT INTO URL(ID, ORIGINAL_URL, TOKEN, REDIRECT_TYPE, HIT_COUNT, ACCOUNT_ID) VALUES(2, 'http://testtwo.com', '3dFQlsf', 301, 3, 2);
INSERT INTO URL(ID, ORIGINAL_URL, TOKEN, REDIRECT_TYPE, HIT_COUNT, ACCOUNT_ID) VALUES(3, 'http://testthree.com', '05Lga2', 302, 4, 1);